sudo: required
language: cpp
compiler: gcc
dist: trusty

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install: 
  - sudo apt-get install -qq g++-7 
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 90

script: 
  - wget https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - chmod +x ./gcc-fix.sh
  - chmod +x ./travis.sh
  - sudo bash ./gcc-fix.sh
  - sudo bash ./travis.sh

after_success:
  - sudo bash upload.sh $TRAVIS_BUILD_DIR/msm8916/Ice*.zip

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/

cache:
  - ccache

group: travis_latest
os: linux
